# Generated by Django 6.0.6 on 2026-06-15 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hospital', '0002_vitalsign_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages', to=settings.AUTH_USER_MODEL),
        ),
    ]
